# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: rusz.dev
email: em@rusz.dev
description: >- # this means to ignore newlines until "baseurl:"
  Blog and portfolio for Em (Ethan) Ruszanowski.
github_username: emrusz
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/New_York

include:
  - _pages
  - .well-known

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Em (Ethan) Ruszanowski"
  avatar: "/assets/images/avatar.png"
  bio: "Data engineer, polyglot developer, and RIT Computing and Information Technologies alum."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:em@rusz.dev"
    - label: "Forgejo"
      icon: "fab fa-fw fa-git-alt"
      url: "https://git.rusz.dev/em"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emrusz"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://infosec.exchange/@rusz"
    - label: "Matrix"
      icon: "fas fa-fw fa-paper-plane"
      url: "https://matrix.to/#/@ruszdev:matrix.org"
    - label: "XMPP"
      icon: "fas fa-fw fa-paper-plane"
      url: "xmpp://ruszdev@macaw.me"

footer:
  links:
    - label: "Forgejo"
      icon: "fab fa-fw fa-git-alt"
      url: "https://git.rusz.dev/em"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/emrusz"
    - label: "OpenPGP"
      icon: "fas fa-fw fa-lock"
      url: "https://rusz.dev/pgp"
    - label: "Status"
      icon: "fas fa-fw fa-heartbeat"
      url: "https://status.rusz.dev"

after_footer_scripts:
  - assets/js/clipboard.js

social:
  type:
  names:
  links:
    - "https://github.com/emrusz"
    - "https://infosec.exchange/@rusz"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
